site :opscode

cookbook 'mongodb'
cookbook 'rabbitmq'
cookbook 'redisio'
cookbook 'npm'
cookbook 'nodejs' , git: 'git@github.com:mdxp/nodejs-cookbook.git'

cookbook 'varnish'
cookbook 'gunicorn'
cookbook 'supervisor'
cookbook 'build-essential'
cookbook 'apt'
cookbook 'yum'
cookbook 'yum-epel'
cookbook 'git'
cookbook 'sqlite'
cookbook 'ulimit'
cookbook 'nfs'
cookbook 'line'
cookbook 'python'
cookbook 'runit'
cookbook 'uwsgi'